# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-27 22:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
    ]

    operations = [
        migrations.CreateModel(
            name='FonoUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(max_length=50, unique=True, verbose_name='Nome do usu\xe1rio')),
                ('email', models.EmailField(blank=True, db_index=True, max_length=255, null=True, unique=True, verbose_name='E-mail')),
                ('enrollment', models.CharField(max_length=20, unique=True, verbose_name='Matr\xedcula')),
                ('supervisor', models.CharField(max_length=100, verbose_name='Supervisor')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Status de suporte')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('full_name', models.CharField(max_length=100, verbose_name='Nome completo')),
                ('short_name', models.CharField(max_length=50, verbose_name='Nome abreviado')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='data de inscri\xe7\xe3o')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='\xfaltima atualiza\xe7\xe3o')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'usu\xe1rio',
                'verbose_name_plural': 'usu\xe1rios',
            },
        ),
        migrations.CreateModel(
            name='PatientUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('identidade', models.CharField(max_length=15, unique=True, verbose_name='Identidade')),
                ('cpf', models.CharField(max_length=20, unique=True, verbose_name='CPF')),
                ('idate', models.IntegerField(verbose_name='Idade')),
                ('data_nascimento', models.DateField(verbose_name='Data de Nascimento')),
                ('naturalidade', models.CharField(blank=True, max_length=30, null=True, verbose_name='Naturalidade')),
                ('profissao', models.CharField(blank=True, max_length=30, null=True, verbose_name='Profiss\xe3o')),
                ('estado_civil', models.CharField(blank=True, max_length=20, null=True, verbose_name='Estado Civil')),
                ('pai', models.CharField(blank=True, max_length=100, null=True, verbose_name='Pai')),
                ('mae', models.CharField(blank=True, max_length=100, null=True, verbose_name='M\xe3e')),
                ('escolaridade', models.CharField(blank=True, max_length=30, null=True, verbose_name='Escolaridade')),
                ('endereco', models.CharField(blank=True, max_length=255, null=True, verbose_name='Endere\xe7o')),
                ('bairro', models.CharField(blank=True, max_length=50, null=True, verbose_name='Bairro')),
                ('cep', models.CharField(blank=True, max_length=10, null=True, verbose_name='CEP')),
                ('fone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone')),
                ('contato', models.CharField(blank=True, max_length=100, null=True, verbose_name='Contato')),
                ('encaminhado_por', models.CharField(max_length=100, verbose_name='Encaminhado por')),
                ('hipostese_diagnostico', models.CharField(blank=True, max_length=100, null=True, verbose_name='Hip\xf3tese de Diagn\xf3stico')),
                ('motivo_consulta', models.TextField(blank=True, null=True, verbose_name='Motivo da Consulta')),
                ('autorizacao', models.CharField(max_length=50, verbose_name='Autoriza\xe7\xe3o')),
                ('valor_sessao', models.FloatField(verbose_name='Valor da Sess\xe3o')),
                ('desconto', models.FloatField(verbose_name='Desconto')),
                ('inicio_atentimento', models.DateField(verbose_name='In\xedcio do Atendimento')),
                ('termino_atendimento', models.DateField(blank=True, null=True, verbose_name='T\xe9rmino do Atendimento')),
                ('treater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paciente', to=settings.AUTH_USER_MODEL, verbose_name='Tratador')),
            ],
            options={
                'verbose_name': 'paciente',
                'verbose_name_plural': 'pacientes',
            },
        ),
    ]
