# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-29 18:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patientuser',
            old_name='hipostese_diagnostico',
            new_name='hipotese_diagnostico',
        ),
        migrations.RenameField(
            model_name='patientuser',
            old_name='inicio_atentimento',
            new_name='inicio_atendimento',
        ),
    ]
