# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-29 18:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20160329_1523'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patientuser',
            old_name='idate',
            new_name='idade',
        ),
    ]
