# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-27 22:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientSessionActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField(verbose_name='Descri\xe7\xe3o')),
            ],
            options={
                'verbose_name': 'Atividade da sess\xe3o',
                'verbose_name_plural': 'Atividades da sess\xe3o',
            },
        ),
        migrations.CreateModel(
            name='PatientSessionContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField(verbose_name='Descri\xe7\xe3o')),
            ],
            options={
                'verbose_name': 'Conteudo da sess\xe3o',
                'verbose_name_plural': 'Conteudos da sess\xe3o',
            },
        ),
        migrations.CreateModel(
            name='PatientSessionObjective',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField(verbose_name='Descri\xe7\xe3o')),
            ],
            options={
                'verbose_name': 'Objetivo da sess\xe3o',
                'verbose_name_plural': 'Objetivos da sess\xe3o',
            },
        ),
        migrations.CreateModel(
            name='PatientSessionObservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField(verbose_name='Descri\xe7\xe3o')),
            ],
            options={
                'verbose_name': 'CObserva\xe7\xe3o da sess\xe3o',
                'verbose_name_plural': 'Observa\xe7\xf5es da sess\xe3o',
            },
        ),
        migrations.CreateModel(
            name='PatientSessions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sessao', models.IntegerField(verbose_name='N\xfamero da sess\xe3o')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planejamento_diario', to='accounts.PatientUser')),
            ],
            options={
                'verbose_name': 'sess\xe3o do paciente',
                'verbose_name_plural': 'sess\xf5es do paciente',
            },
        ),
        migrations.CreateModel(
            name='PatientTherapy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conduta', models.TextField(unique=True, verbose_name='Conduta terap\xeautica')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planejamento_terapeutico', to='accounts.PatientUser')),
            ],
            options={
                'verbose_name': 'Planejamento terap\xeautico',
                'verbose_name_plural': 'Planejamentos terap\xeauticos',
            },
        ),
        migrations.AddField(
            model_name='patientsessionobservation',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observacao', to='patients.PatientSessions'),
        ),
        migrations.AddField(
            model_name='patientsessionobjective',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objetivo', to='patients.PatientSessions'),
        ),
        migrations.AddField(
            model_name='patientsessioncontent',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conteudo', to='patients.PatientSessions'),
        ),
        migrations.AddField(
            model_name='patientsessionactivity',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atividade', to='patients.PatientSessions'),
        ),
        migrations.AlterUniqueTogether(
            name='patienttherapy',
            unique_together=set([('patient', 'conduta')]),
        ),
        migrations.AlterUniqueTogether(
            name='patientsessions',
            unique_together=set([('patient', 'sessao')]),
        ),
    ]
