# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-28 15:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientTherapyConduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField(verbose_name='Descri\xe7\xe3o')),
                ('conduct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conduta_fonoaudiologica', to='patients.PatientTherapy')),
            ],
            options={
                'verbose_name': 'Conduta Fonoaudiol\xf3gica',
                'verbose_name_plural': 'Condutas Fonoaudiol\xf3gicas',
            },
        ),
        migrations.AlterModelOptions(
            name='patientsessionobservation',
            options={'verbose_name': 'Observa\xe7\xe3o da sess\xe3o', 'verbose_name_plural': 'Observa\xe7\xf5es da sess\xe3o'},
        ),
    ]
